package vista;
import java.text.SimpleDateFormat;

import javax.swing.JOptionPane;

import controlador.ControladorRegistrarMostrarVentas;

public class VistaRegMostVentas extends javax.swing.JFrame {
    ControladorRegistrarMostrarVentas ctlRegMosVentas;
    
    public static void main(String[] args) {
        VistaRegMostVentas objViewRegMostVentas = new VistaRegMostVentas();
        objViewRegMostVentas.setVisible(true);
    }
    
    
    public VistaRegMostVentas() {
        initComponents();
        this.ctlRegMosVentas = new ControladorRegistrarMostrarVentas(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanelConsulta = new javax.swing.JPanel();
        jlbFecha = new javax.swing.JLabel();
        jLabelProducto = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        btnRegistrarVenta = new javax.swing.JButton();
        btnMostrarVentas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        jLabelHistorial = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        bgTituloRegVentas = new javax.swing.JPanel();
        jLabeTituloRegistroVentas = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        bgPanelConsulta.setBackground(new java.awt.Color(255, 255, 255));
        bgPanelConsulta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbFecha.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jlbFecha.setText("Fecha:");
        bgPanelConsulta.add(jlbFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabelProducto.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabelProducto.setText("Producto:");
        bgPanelConsulta.add(jLabelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabelCantidad.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabelCantidad.setText("Cantidad:");
        bgPanelConsulta.add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jLabelTotal.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabelTotal.setText("Total:");
        bgPanelConsulta.add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));
        bgPanelConsulta.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 250, -1));

        btnRegistrarVenta.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnRegistrarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botones/guardar.png"))); // NOI18N
        btnRegistrarVenta.setText("GUARDAR");
        btnRegistrarVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarVentaMouseClicked(evt);
            }
        });
        bgPanelConsulta.add(btnRegistrarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 160, -1));

        btnMostrarVentas.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnMostrarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botones/productos.png"))); // NOI18N
        btnMostrarVentas.setText("VER VENTAS");
        btnMostrarVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarVentasMouseClicked(evt);
            }
        });
        bgPanelConsulta.add(btnMostrarVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 180, -1));

        tblVentas.setAutoCreateRowSorter(true);
        tblVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Producto", "Cantidad", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVentas);
        if (tblVentas.getColumnModel().getColumnCount() > 0) {
            tblVentas.getColumnModel().getColumn(0).setResizable(false);
        }

        bgPanelConsulta.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, 290));

        jLabelHistorial.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabelHistorial.setText("Historial");
        bgPanelConsulta.add(jLabelHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));
        bgPanelConsulta.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 250, -1));

        bgTituloRegVentas.setBackground(new java.awt.Color(204, 0, 204));

        jLabeTituloRegistroVentas.setBackground(new java.awt.Color(255, 255, 255));
        jLabeTituloRegistroVentas.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        jLabeTituloRegistroVentas.setForeground(new java.awt.Color(255, 255, 255));
        jLabeTituloRegistroVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeTituloRegistroVentas.setText("Registro de Ventas");

        javax.swing.GroupLayout bgTituloRegVentasLayout = new javax.swing.GroupLayout(bgTituloRegVentas);
        bgTituloRegVentas.setLayout(bgTituloRegVentasLayout);
        bgTituloRegVentasLayout.setHorizontalGroup(
            bgTituloRegVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgTituloRegVentasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabeTituloRegistroVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bgTituloRegVentasLayout.setVerticalGroup(
            bgTituloRegVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgTituloRegVentasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabeTituloRegistroVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bgPanelConsulta.add(bgTituloRegVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 110));
        bgPanelConsulta.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 250, -1));
        bgPanelConsulta.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 250, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 515, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgPanelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarVentaMouseClicked
    this.registrarVenta();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarVentaMouseClicked

    private void btnMostrarVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarVentasMouseClicked
    this.mostrarHistorial();        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarVentasMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanelConsulta;
    private javax.swing.JPanel bgTituloRegVentas;
    private javax.swing.JButton btnMostrarVentas;
    private javax.swing.JButton btnRegistrarVenta;
    private javax.swing.JLabel jLabeTituloRegistroVentas;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelHistorial;
    private javax.swing.JLabel jLabelProducto;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbFecha;
    public javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

  
    
    private void mostrarHistorial(){
        String[] columnas = {"Fecha", "Producto","Cantidad","Total"};
        this.ctlRegMosVentas.mostrarHistorial(columnas);
            
    }
    
    private void limpiarCajas(){
        this.txtFecha.setText("");
        this.txtProducto.setText("");
        this.txtCantidad.setText("");
        this.txtTotal.setText("");
   
   
    
    }

    private void registrarVenta() {
    
    this.ctlRegMosVentas.agregarVenta(
        this.txtFecha.getText(),
        this.txtProducto.getText(),
        Integer.parseInt(this.txtCantidad.getText()),
        Double.parseDouble(this.txtTotal.getText())
    );

    this.limpiarCajas();
}
    
}
