package vista;
import controlador.ControladorAgregarMostrarContactos;

public class VistaContactos extends javax.swing.JFrame {
    ControladorAgregarMostrarContactos ctlAggMosContact;
    
    public static void main(String[] args) {
        VistaContactos objViewContact = new VistaContactos();
        objViewContact.setVisible(true);
    }
    
    
    public VistaContactos() {
        initComponents();
        this.ctlAggMosContact = new ControladorAgregarMostrarContactos(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanelConsulta = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnMostrarContactos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContactos = new javax.swing.JTable();
        jLabelTituloContactos = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabeTituloAgenda = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        bgPanelConsulta.setBackground(new java.awt.Color(255, 255, 255));
        bgPanelConsulta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombre.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabelNombre.setText("Nombre:");
        bgPanelConsulta.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabelTelefono.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabelTelefono.setText("Teléfono:");
        bgPanelConsulta.add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabelEmail.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabelEmail.setText("Email:");
        bgPanelConsulta.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));
        bgPanelConsulta.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 250, -1));
        bgPanelConsulta.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 250, -1));

        btnAgregar.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botones/contactos.png"))); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        bgPanelConsulta.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 140, -1));

        btnMostrarContactos.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnMostrarContactos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botones/listacontactos.png"))); // NOI18N
        btnMostrarContactos.setText("MOSTRAR CONTACTOS");
        btnMostrarContactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarContactosMouseClicked(evt);
            }
        });
        btnMostrarContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarContactosActionPerformed(evt);
            }
        });
        bgPanelConsulta.add(btnMostrarContactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 240, -1));

        tblContactos.setAutoCreateRowSorter(true);
        tblContactos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblContactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Telefono", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblContactos);
        if (tblContactos.getColumnModel().getColumnCount() > 0) {
            tblContactos.getColumnModel().getColumn(0).setResizable(false);
        }

        bgPanelConsulta.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, 290));

        jLabelTituloContactos.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabelTituloContactos.setText("CONTACTOS");
        bgPanelConsulta.add(jLabelTituloContactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));
        bgPanelConsulta.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 250, -1));

        jLabeTituloAgenda.setBackground(new java.awt.Color(0, 0, 0));
        jLabeTituloAgenda.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        jLabeTituloAgenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeTituloAgenda.setText("AGENDA");
        bgPanelConsulta.add(jLabeTituloAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 110));

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        bgPanelConsulta.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgPanelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
    this.guardarContacto();        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnMostrarContactosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarContactosMouseClicked
    this.mostrarContactos();        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarContactosMouseClicked

    private void btnMostrarContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarContactosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarContactosActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanelConsulta;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnMostrarContactos;
    private javax.swing.JLabel jLabeTituloAgenda;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTituloContactos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblContactos;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

  
    
    private void mostrarContactos(){
        String[] columnas = {"Nombre", "Telefono","Email"};
        this.ctlAggMosContact.mostrarContactos(columnas);
            
    }
    
    private void limpiarCajas(){
        this.txtNombre.setText("");
        this.txtTelefono.setText("");
        this.txtEmail.setText("");
   
   
    
    }

    private void guardarContacto() {
        this.ctlAggMosContact.agregarContacto(this.txtNombre.getText(),
        this.txtTelefono.getText(),
        this.txtEmail.getText());
        
        this.limpiarCajas();
        
    }
    
}
