package vista;
import controlador.ControladorGuardarMostrarInventario;

public class VistaInventario extends javax.swing.JFrame {
    ControladorGuardarMostrarInventario ctlGuarMostInventario;
    
    public static void main(String[] args) {
        VistaInventario objViewInventario = new VistaInventario();
        objViewInventario.setVisible(true);
    }
    
    
    public VistaInventario() {
        initComponents();
        this.ctlGuarMostInventario = new ControladorGuardarMostrarInventario(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanelConsulta = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnMostrarInventario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jLabelTituloListaInventario = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabelID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabeTituloInventario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        bgPanelConsulta.setBackground(new java.awt.Color(255, 255, 255));
        bgPanelConsulta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombre.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabelNombre.setText("Nombre:");
        bgPanelConsulta.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabelPrecio.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabelPrecio.setText("Precio:");
        bgPanelConsulta.add(jLabelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jLabelCantidad.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabelCantidad.setText("Cantidad:");
        bgPanelConsulta.add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));
        bgPanelConsulta.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 250, -1));
        bgPanelConsulta.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 250, -1));

        btnGuardar.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botones/guardarIn.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        bgPanelConsulta.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        btnMostrarInventario.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnMostrarInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botones/inventario.png"))); // NOI18N
        btnMostrarInventario.setText("MOSTRAR INVENTARIO");
        btnMostrarInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarInventarioMouseClicked(evt);
            }
        });
        bgPanelConsulta.add(btnMostrarInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 240, -1));

        tblProductos.setAutoCreateRowSorter(true);
        tblProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Precio", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProductos);
        if (tblProductos.getColumnModel().getColumnCount() > 0) {
            tblProductos.getColumnModel().getColumn(0).setResizable(false);
        }

        bgPanelConsulta.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, 290));

        jLabelTituloListaInventario.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabelTituloListaInventario.setText("Inventario");
        bgPanelConsulta.add(jLabelTituloListaInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));
        bgPanelConsulta.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 250, -1));

        jLabelID.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabelID.setText("ID:");
        bgPanelConsulta.add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));
        bgPanelConsulta.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 250, -1));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabeTituloInventario.setBackground(new java.awt.Color(255, 255, 255));
        jLabeTituloInventario.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        jLabeTituloInventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeTituloInventario.setText("INVENTARIO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabeTituloInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabeTituloInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bgPanelConsulta.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 515, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgPanelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
    this.guardarProducto();        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnMostrarInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarInventarioMouseClicked
    this.mostrarInventario();        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarInventarioMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanelConsulta;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrarInventario;
    private javax.swing.JLabel jLabeTituloInventario;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelTituloListaInventario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

  
    
    private void mostrarInventario(){
        String[] columnas = {"ID", "Nombre","Precio","Cantidad"};
        this.ctlGuarMostInventario.mostrarInventario(columnas);
            
    }
    
    private void limpiarCajas(){
        this.txtID.setText("");
        this.txtNombre.setText("");
        this.txtPrecio.setText("");
        this.txtCantidad.setText("");
   
   
    
    }

    private void guardarProducto() {
        this.ctlGuarMostInventario.agregarProducto(
        this.txtID.getText(),
        this.txtNombre.getText(),
        Integer.parseInt(this.txtCantidad.getText()),
        Double.parseDouble(this.txtPrecio.getText()));
        
        this.limpiarCajas();
        
    }
    
}
