package vista;
import controlador.ControladorRegistrarConsultarEstudiante;

public class VistaRegistrarConsultarEstudiante extends javax.swing.JFrame {
    ControladorRegistrarConsultarEstudiante ctlRegConEst;
    
    public VistaRegistrarConsultarEstudiante() {
        initComponents();
        this.ctlRegConEst = new ControladorRegistrarConsultarEstudiante(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanelConsulta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNumControl = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCarrera = new javax.swing.JLabel();
        jLabelPromedio = new javax.swing.JLabel();
        txtNumControl = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cboCarrera = new javax.swing.JComboBox<>();
        txtPromedio = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstudiantes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        bgPanelConsulta.setBackground(new java.awt.Color(255, 255, 255));
        bgPanelConsulta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel1.setText("REGISTRAR ESTUDIANTE");
        bgPanelConsulta.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 30, 420, -1));

        jLabelNumControl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabelNumControl.setText("Num. Control:");
        bgPanelConsulta.add(jLabelNumControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabelNombre.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabelNombre.setText("Nombre:");
        bgPanelConsulta.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabelCarrera.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabelCarrera.setText("Carrera:");
        bgPanelConsulta.add(jLabelCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabelPromedio.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabelPromedio.setText("Promedio:");
        bgPanelConsulta.add(jLabelPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));
        bgPanelConsulta.add(txtNumControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 250, -1));
        bgPanelConsulta.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 250, -1));

        cboCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingeniería en Agronomía", "Licenciatura en Biología", "Ingeniería Forestal", "Ingeniería Informática", "Ingeniería en Tecnologías de la Información y Comunicaciones", "Ingeniería en Ciencia de Datos", "Ingeniería Ambiental", "Ingeniería en Gestión Empresarial" }));
        bgPanelConsulta.add(cboCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 250, -1));
        bgPanelConsulta.add(txtPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 250, -1));

        btnGuardar.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botones/guardar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        bgPanelConsulta.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        btnListar.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botones/listar.png"))); // NOI18N
        btnListar.setText("LISTAR");
        btnListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarMouseClicked(evt);
            }
        });
        bgPanelConsulta.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 130, -1));

        tblEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num. Control", "Nombre", "Carrera", "Promedio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEstudiantes);

        bgPanelConsulta.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, 300));

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        bgPanelConsulta.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgPanelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
    this.guardarRegistro();        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarMouseClicked
    this.listarEstudiante();        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanelConsulta;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnListar;
    private javax.swing.JComboBox<String> cboCarrera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCarrera;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumControl;
    private javax.swing.JLabel jLabelPromedio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblEstudiantes;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumControl;
    private javax.swing.JTextField txtPromedio;
    // End of variables declaration//GEN-END:variables

    private void guardarRegistro() {
    this.ctlRegConEst.registrarEstudiante(this.txtNumControl.getText(),
                this.txtNombre.getText(), 
                this.cboCarrera.getSelectedItem().toString(),
                Double.parseDouble(this.txtPromedio.getText()));
    
    this.limpiarCajas();

    }
    
    private void listarEstudiante(){
        String[] columnas = {"Num. Control", "Nombre", "Carrera","Promedio"};                      
        this.ctlRegConEst.listarEst(columnas);  
            
    }
    
    private void limpiarCajas(){
        this.txtNumControl.setText("");
        this.txtPromedio.setText("");
        this.txtNombre.setText("");                
   
   
    
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrarConsultarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrarConsultarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrarConsultarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrarConsultarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistrarConsultarEstudiante().setVisible(true);
            }
        });
    }
    
    
}
