package vista;
import controlador.ControladorLogin;

public class VistaLogin extends javax.swing.JFrame {
    VistaRegistro viewRegistro;
    ControladorLogin ctrlLogin;
    
    public VistaLogin(VistaRegistro viewRegistro) {
        initComponents();
        this.viewRegistro = viewRegistro;
        this.ctrlLogin = new ControladorLogin(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanelConsulta = new javax.swing.JPanel();
        fondoTitulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCarrera = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jpfPasword = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        txtMensaje = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        bgPanelConsulta.setBackground(new java.awt.Color(255, 255, 255));
        bgPanelConsulta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoTitulo.setBackground(new java.awt.Color(0, 0, 0));
        fondoTitulo.setFont(new java.awt.Font("Stencil", 0, 50)); // NOI18N
        fondoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoTitulo.setText("LOGIN");
        bgPanelConsulta.add(fondoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 520, -1));

        jLabelNombre.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabelNombre.setText("Usuario:");
        bgPanelConsulta.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabelCarrera.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabelCarrera.setText("Contraseña:");
        bgPanelConsulta.add(jLabelCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));
        bgPanelConsulta.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 250, -1));

        btnIngresar.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botones/ingresar.png"))); // NOI18N
        btnIngresar.setText("INGRESAR");
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarMouseClicked(evt);
            }
        });
        bgPanelConsulta.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        btnRegresar.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botones/regresar.png"))); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        bgPanelConsulta.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));
        bgPanelConsulta.add(jpfPasword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 250, -1));

        jPanel1.setBackground(new java.awt.Color(255, 51, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bgPanelConsulta.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, -1));
        bgPanelConsulta.add(txtMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
    viewRegistro.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseClicked
    this.ingresar();        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanelConsulta;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel fondoTitulo;
    private javax.swing.JLabel jLabelCarrera;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jpfPasword;
    public javax.swing.JTextField txtMensaje;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void ingresar() {
    String usuario = this.txtUsuario.getText();
    String password = new String(this.jpfPasword.getPassword());

    this.ctrlLogin.login(usuario, password);
    }
    
    
    
    
    
}
