package vista;
import controlador.ControladorRegistrar;
import java.awt.Color;
public class VistaRegistro extends javax.swing.JFrame {
    ControladorRegistrar ctrlRegistrar;
    public VistaRegistro() {
        initComponents();
        this.ctrlRegistrar = new ControladorRegistrar(this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelbackground = new javax.swing.JPanel();
        jLabelContornoTitulo = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnIniciarSesion = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPasword = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelbackground.setBackground(new java.awt.Color(204, 204, 204));
        jPanelbackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelContornoTitulo.setFont(new java.awt.Font("Stencil", 0, 49)); // NOI18N
        jLabelContornoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelContornoTitulo.setText("REGISTRO");
        jPanelbackground.add(jLabelContornoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 630, -1));

        btnRegistrar.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botones/registrar.png"))); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setToolTipText("");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        jPanelbackground.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 180, 40));

        btnCerrar.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botones/cerrar.png"))); // NOI18N
        btnCerrar.setText("CERRAR");
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarMouseExited(evt);
            }
        });
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanelbackground.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 180, 40));

        btnIniciarSesion.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        btnIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botones/iniciarCesion.png"))); // NOI18N
        btnIniciarSesion.setText("INICIAR SESIÓN");
        btnIniciarSesion.setToolTipText("");
        btnIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseClicked(evt);
            }
        });
        jPanelbackground.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 190, 40));

        jLabelUsuario.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabelUsuario.setText("Usuario:");
        jPanelbackground.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 80, -1));

        jLabelPassword.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabelPassword.setText("Contraseña:");
        jPanelbackground.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));
        jPanelbackground.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 220, -1));
        jPanelbackground.add(txtPasword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 220, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelbackground, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelbackground, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseEntered
    btnCerrar.setBackground(Color.red);        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarMouseEntered

    private void btnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseExited
    btnCerrar.setBackground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarMouseExited

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
    VistaLogin objVistaRegtrEst = new VistaLogin(this);  
    objVistaRegtrEst.setVisible(true);
    this.registrarUsuario();
    this.setVisible(false);
   
    // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
    System.exit(0);       // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseClicked
    VistaLogin login = new VistaLogin(this);
    login.setVisible(true);
    this.setVisible(false);


    }//GEN-LAST:event_btnIniciarSesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabelContornoTitulo;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanelbackground;
    private javax.swing.JTextField txtPasword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void registrarUsuario() {
    String usuario = this.txtUsuario.getText();
    String password = this.txtPasword.getText();

    this.ctrlRegistrar.registrar(usuario, password);    }
}
